name: 'AppSec Scanner'
description: 'Runs SAST (Semgrep), SCA (Trivy), and IaC (terrascan) scans'
author: 'Nir Alon'
branding:
  icon: 'activity'
  color: 'blue'
  
runs:
  using: 'composite'
  steps:
    - name: Install Semgrep
      run: |
        set -e -o pipefail
        pip install semgrep --quiet > /dev/null
      shell: bash

    - name: Run Semgrep SAST
      run: semgrep scan --config auto . || echo "Semgrep exited with non-zero code"
      shell: bash

    - name: Install Terrascan
      run: |
        set -e -o pipefail
        curl -sL "$(curl -s https://api.github.com/repos/tenable/terrascan/releases/latest | grep -o -E "https://.+?_Linux_x86_64.tar.gz")" > terrascan.tar.gz
        tar -xf terrascan.tar.gz terrascan > /dev/null 2>&1
        sudo install terrascan /usr/local/bin > /dev/null 2>&1
        rm terrascan terrascan.tar.gz
      shell: bash

    - name: Run terrascan IaC Scan
      run: terrascan scan . || echo "Terrascan exited with non-zero code"
      shell: bash
    
    - name: Install and Run Trivy SCA Scan
      run: |
        set -e -o pipefail
        curl -sSL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin > /dev/null
        trivy fs --exit-code 0 --format table .
      shell: bash
